services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ualf
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ualf"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build:
      context: ..
      dockerfile: infra/api.Dockerfile
      target: api
    environment:
      REDIS_URL: "redis://redis:6379/0"
      PYTHONUNBUFFERED: "1"
      PORT: "8000"
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: ..
      dockerfile: infra/web.Dockerfile
      target: run
    environment:
      NEXT_PUBLIC_API_URL: "http://api:8000"
      NEXT_TELEMETRY_DISABLED: "1"
    ports:
      - "3001:3001"
    depends_on:
      - api
